### ISSUE TITLE
Want a Hqporner downloader 

### ISSUE THREAD

**Issue by basharjehadi** [Bbalduzz/PornHub-downloader#3]
Please share a script to download videos from hqporner.com

**Comment by Bbalduzz** [comment]
sure, but it is gonna be a bit slow:

```
import requests
from bs4 import BeautifulSoup
from requests_html import HTMLSession
import numpy
import colorama

user_input = input('Enter the URL of the video or the PATH to the text file: ')
choice= input('choose quality: 360 / 720 / 1080 (DEFAULT): ')

if '.html' in user_input:
    URLS = user_input
elif '.txt' in user_input:
    with open(user_input, 'r') as handler:
        URLS = handler.readlines()

for URL in URLS:
    page = requests.get(URL)
    soup = BeautifulSoup(page.content, 'html.parser')
    iframes = soup.find_all('iframe')
    video_iframe = iframes[0]
    video_src = video_iframe['src']
    video_url = f'https:{video_src}'
    video_name = soup.find(class_='main-h1').contents[0].strip()
    print('Video Found:', video_name)

    session = HTMLSession()
    r = session.get(video_url)
    page = r.html
    page.render()  # this call executes the js in the page
    video_links = page.links
    qualities = numpy.array(list(video_links))
    video_1080 = qualities[1]
    video_720 = qualities[2]
    video_360 = qualities[0]


    if choice == '' or choice == '1080':
        url_video = f'https:{video_1080}'
        print('Downloading...')
        with requests.get(url_video, stream=True) as r:
            with open(f'{video_name}.mp4', 'wb') as f:
                for chunk in r.iter_content(chunk_size=16*1024):
                    f.write(chunk)
        print('done')
    elif choice == '360':
        url_video = f'https:{video_360}'
        r = requests.get(url_video, stream=True)
        print('Downloading... be patient')
        with open(f'{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
        print('done')
    elif choice == '720':
        url_video = f'https:{video_720}'
        r = requests.get(url_video, stream=True)
        print('Downloading... be patient')
        with open(f'{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
        print('done')
    else:
        print('no video found')
```

**Comment by basharjehadi** [comment]
Hello
Please can you add the functionality where i can mentioned the path where
the videos should be downloaded?
Sincerely
Md Abul Bashar Jehadi

**Comment by basharjehadi** [comment]
Also please can you add utf-8 for writing title so that spaces or other
characters will be removed from title?
Sincerely
Md Abul Bashar Jehadi

**Comment by basharjehadi** [comment]
Hello
Good is throwing error please tell me what to do ?
Sincerely
MD Abul Bashar Jehadi

**Comment by basharjehadi** [comment]
Hello,
Code is throwing  error. Please tell me what to do?
Sincerely
Md Abul Bashar Jehadi

**Comment by Bbalduzz** [comment]
ok mate, here you go, consider leaving a star on this repo :)

```
import requests
from bs4 import BeautifulSoup
from requests_html import HTMLSession
import numpy
from os import path
import os

URL = input('Enter the URL of the video or the PATH to the text file: ')
choice= input('choose quality: 360 / 720 / 1080 (DEFAULT): ')

folder_dir = 'path-to-folder' # put here the path of your folder

page = requests.get(URL)
soup = BeautifulSoup(page.content, 'html.parser')
iframes = soup.find_all('iframe')
video_iframe = iframes[0]
video_src = video_iframe['src']
video_url = f'https:{video_src}'
video_name = soup.find(class_='main-h1').contents[0].strip()
video_name = video_name.replace(" ","-")
print('Video Found:', video_name)

session = HTMLSession()
r = session.get(video_url)
page = r.html
page.render()  # this call executes the js in the page
video_links = page.links
qualities = numpy.array(list(video_links))
video_1080 = qualities[1]
video_720 = qualities[2]
video_360 = qualities[0]


if choice == '' or choice == '1080':
    url_video = f'https:{video_1080}'
    print('Downloading...')
    download_path = f'{folder_dir}/hqporner/1080/'
    if os.path.exists(download_path):
        pass
    else:
        os.makedirs(download_path)
    with requests.get(url_video, stream=True) as r:
        with open(f'{download_path}/1080/{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
    print('done')
elif choice == '360':
    url_video = f'https:{video_360}'
    print('Downloading...')
    download_path = f'{folder_dir}/hqporner/360/'
    if os.path.exists(download_path):
        pass
    else:
        os.makedirs(download_path)
    with requests.get(url_video, stream=True) as r:
        with open(f'{download_path}{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
    print('done')
elif choice == '720':
    url_video = f'https:{video_720}'
    print('Downloading...')
    download_path = f'{folder_dir}/hqporner/720/'
    if os.path.exists(download_path):
        pass
    else:
        os.makedirs(download_path)
    with requests.get(url_video, stream=True) as r:
        with open(f'{download_path}{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
    print('done')
else:
    print('no video found')
```

**Comment by basharjehadi** [comment]
I have gave you start of course.You are Fantastic.Can you make a script for
this site please?
 https://milfnut.com/
Mainly i need a script for downloading videos hosted in  streamsb
server.Can you please help me?
Sincerely
Bashar

**Comment by basharjehadi** [comment]
Hello
I am trying to run your given script on my server and local machine but it
is throwing an error. Can you please help to fix it? I beg you.
Sincerely
Md ABul bashar jehadi

**Comment by Bbalduzz** [comment]
what is the error? Can u paste it here?

**Comment by basharjehadi** [comment]
if i run in my server then this issue is coming
Traceback (most recent call last):
  File "/home/cdn_hdpornshot_com/hqpornerdownloader/hqpornerdownloader.py",
line 26, in <module>
    page.render()  # this call executes the js in the page
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/requests_html.py",
line 586, in render
    self.browser = self.session.browser  # Automatically create a event
loop and browser
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/requests_html.py",
line 730, in browser
    self._browser = self.loop.run_until_complete(super().browser)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in
run_until_complete
    return future.result()
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/requests_html.py",
line 714, in browser
    self._browser = await
pyppeteer.launch(ignoreHTTPSErrors=not(self.verify), headless=True,
args=self.__browser_args)
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/pyppeteer/launcher.py",
line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/pyppeteer/launcher.py",
line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/pyppeteer/launcher.py",
line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by basharjehadi** [comment]
If I run the script on a local machine, then this error comes.
$ python hqpornerdownloader.py
Enter the URL of the video or the PATH to the text file:
https://hqporner.com/hdporn/108085-do_you_mind_if_my_girlfriend_joins.html
choose quality: 360 / 720 / 1080 (DEFAULT): 720
Video Found: do-you-mind-if-my-girlfriend-joins?
Traceback (most recent call last):
  File "hqpornerdownloader.py", line 31, in <module>
    video_720 = qualities[1]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by basharjehadi** [comment]
Hello
I am Eagerly waiting for your email.please help me to run your script
perfectly.please please please
Sincerely
Md Abul Bashar Jehadi

**Comment by Bbalduzz** [comment]
I changed a bit the code. I tried and it worked for me, let me know if u encounter any other error

```
import requests
from bs4 import BeautifulSoup
from requests_html import HTMLSession
import numpy
import colorama

user_input = input('Enter the URL of the video or the PATH to the text file: ')
choice= input('choose quality: 360 / 720 / 1080 (DEFAULT): ')

URLS = []
if '.html' in user_input:
    URLS.append(user_input)
elif '.txt' in user_input:
    with open(user_input, 'r') as handler:
        URLS.append(handler.readlines())

for URL in URLS:
    page = requests.get(URL)
    soup = BeautifulSoup(page.content, 'html.parser')
    iframes = soup.find_all('iframe')
    video_iframe = iframes[0]
    video_src = video_iframe['src']
    video_url = f'https:{video_src}'
    video_name = soup.find(class_='main-h1').contents[0].strip()
    print('Video Found:', video_name)

    session = HTMLSession()
    r = session.get(video_url)
    page = r.html
    page.render()  # this call executes the js in the page
    video_links = page.links
    qualities = numpy.array(list(video_links))
    video_1080 = qualities[1]
    video_720 = qualities[2]
    video_360 = qualities[0]


    if choice == '' or choice == '1080':
        url_video = f'https:{video_1080}'
        print('Downloading...')
        with requests.get(url_video, stream=True) as r:
            with open(f'{video_name}.mp4', 'wb') as f:
                for chunk in r.iter_content(chunk_size=16*1024):
                    f.write(chunk)
        print('done')
    elif choice == '360':
        url_video = f'https:{video_360}'
        r = requests.get(url_video, stream=True)
        print('Downloading... be patient')
        with open(f'{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
        print('done')
    elif choice == '720':
        url_video = f'https:{video_720}'
        r = requests.get(url_video, stream=True)
        print('Downloading... be patient')
        with open(f'{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
        print('done')
    else:
        print('no video found')
```

**Comment by basharjehadi** [comment]
Hello
if i am giving a single URL then the script is working but if I give the
URL file path then it's not working. This error is coming.

***@***.***:~/hqpornerdownloader$ python3
hqpornerdownloader.py
Enter the URL of the video or the PATH to the text file:
/home/cdn_hdpornshot_com/hqpornerdownloader/url.txt
choose quality: 360 / 720 / 1080 (DEFAULT): 720
Traceback (most recent call last):
  File "/home/cdn_hdpornshot_com/hqpornerdownloader/hqpornerdownloader.py",
line 18, in <module>
    page = requests.get(URL)
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/requests/api.py",
line 73, in get
    return request("get", url, params=params, **kwargs)
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/requests/api.py",
line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/requests/sessions.py",
line 587, in request
    resp = self.send(prep, **send_kwargs)
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/requests/sessions.py",
line 695, in send
    adapter = self.get_adapter(url=request.url)
  File
"/home/cdn_hdpornshot_com/.local/lib/python3.9/site-packages/requests/sessions.py",
line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for "['
https://hqporner.com/hdporn/106325-clean_content_thats_a_promise.html\\n', '
https://hqporner.com/hdporn/87821-one_cock_isnt_enough_for_a_brunette_hottie.html\\n',
'https://hqporner.com/hdporn/87372-dildo-tongue_orgasm_technique.html\\n', '
https://hqporner.com/hdporn/91045-colorful_couple_fantasies.html\\n', '
https://hqporner.com/hdporn/90790-before_her_next_flight.html\\n', '
https://hqporner.com/hdporn/89403-fitness_for_her_sweet_ass.html\\n', '
https://hqporner.com/hdporn/87887-for_sports_purposes.html\\n', '
https://hqporner.com/hdporn/106352-cum_spurt_on_slippery_slope.html\\n', '
https://hqporner.com/hdporn/96165-all_about_business.html\\n', '
https://hqporner.com/hdporn/106966-wow_describes_her_ass_perfectly.html\\n',
'
https://hqporner.com/hdporn/89890-Cassie_Del_Isla_27_years_old_casting.html\\n',
'
https://hqporner.com/hdporn/107371-neighborly_putting_stuff_in_her_butt.html\\n',
'https://hqporner.com/hdporn/88652-London_taxi_drivers_traditions.html\\n',
'https://hqporner.com/hdporn/106131-french_sex_language_translated.html\\n',
'https://hqporner.com/hdporn/87177-sex_domination_in_prison.html\\n']"
***@***.***:~/hqpornerdownloader$

**Comment by basharjehadi** [comment]
Please, man,
you helped me a lot by just fixing the issue of why the .txt file with URLs
is not working.Please

**Comment by basharjehadi** [comment]
Please help me to download from txt file.
Please fix it.

**Comment by Bbalduzz** [comment]
import requests
from bs4 import BeautifulSoup
from requests_html import HTMLSession
import numpy
import colorama

user_input = input('Enter the URL of the video or the PATH to the text file: ')
choice= input('choose quality: 360 / 720 / 1080 (DEFAULT): ')

URLS = []
if '.html' in user_input:
    URLS.append(user_input)
elif '.txt' in user_input:
    with open(user_input, 'r') as handler:
        URLS.append(handler..read().splitlines())

for URL in URLS:
    page = requests.get(URL)
    soup = BeautifulSoup(page.content, 'html.parser')
    iframes = soup.find_all('iframe')
    video_iframe = iframes[0]
    video_src = video_iframe['src']
    video_url = f'https:{video_src}'
    video_name = soup.find(class_='main-h1').contents[0].strip()
    print('Video Found:', video_name)

    session = HTMLSession()
    r = session.get(video_url)
    page = r.html
    page.render()  # this call executes the js in the page
    video_links = page.links
    qualities = numpy.array(list(video_links))
    video_1080 = qualities[1]
    video_720 = qualities[2]
    video_360 = qualities[0]


    if choice == '' or choice == '1080':
        url_video = f'https:{video_1080}'
        print('Downloading...')
        with requests.get(url_video, stream=True) as r:
            with open(f'{video_name}.mp4', 'wb') as f:
                for chunk in r.iter_content(chunk_size=16*1024):
                    f.write(chunk)
        print('done')
    elif choice == '360':
        url_video = f'https:{video_360}'
        r = requests.get(url_video, stream=True)
        print('Downloading... be patient')
        with open(f'{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
        print('done')
    elif choice == '720':
        url_video = f'https:{video_720}'
        r = requests.get(url_video, stream=True)
        print('Downloading... be patient')
        with open(f'{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
        print('done')
    else:
        print('no video found')

**Comment by Bbalduzz** [comment]
import requests
from bs4 import BeautifulSoup
from requests_html import HTMLSession
import numpy
import colorama

user_input = input('Enter the URL of the video or the PATH to the text file: ')
choice= input('choose quality: 360 / 720 / 1080 (DEFAULT): ')

URLS = []
if '.html' in user_input:
    URLS.append(user_input)
elif '.txt' in user_input:
    with open(user_input, 'r') as handler:
        URLS.append(handler..read().splitlines())

for URL in URLS:
    page = requests.get(URL)
    soup = BeautifulSoup(page.content, 'html.parser')
    iframes = soup.find_all('iframe')
    video_iframe = iframes[0]
    video_src = video_iframe['src']
    video_url = f'https:{video_src}'
    video_name = soup.find(class_='main-h1').contents[0].strip()
    print('Video Found:', video_name)

    session = HTMLSession()
    r = session.get(video_url)
    page = r.html
    page.render()  # this call executes the js in the page
    video_links = page.links
    qualities = numpy.array(list(video_links))
    video_1080 = qualities[1]
    video_720 = qualities[2]
    video_360 = qualities[0]


    if choice == '' or choice == '1080':
        url_video = f'https:{video_1080}'
        print('Downloading...')
        with requests.get(url_video, stream=True) as r:
            with open(f'{video_name}.mp4', 'wb') as f:
                for chunk in r.iter_content(chunk_size=16*1024):
                    f.write(chunk)
        print('done')
    elif choice == '360':
        url_video = f'https:{video_360}'
        r = requests.get(url_video, stream=True)
        print('Downloading... be patient')
        with open(f'{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
        print('done')
    elif choice == '720':
        url_video = f'https:{video_720}'
        r = requests.get(url_video, stream=True)
        print('Downloading... be patient')
        with open(f'{video_name}.mp4', 'wb') as f:
            for chunk in r.iter_content(chunk_size=16*1024):
                f.write(chunk)
        print('done')
    else:
        print('no video found')

**Comment by basharjehadi** [comment]
Have you tested it?It's not working

**Comment by basharjehadi** [comment]
Can you make this script just for downloading videos from URLs from a text
file only?
Please please please, please

**Comment by basharjehadi** [comment]
Please, man. I understand you can be very busy. Please help me to download
videos from a txt file.Please
